language: java

jdk:
  - oraclejdk8
sudo: required
dist: trusty
script:
  - ./gradlew --stacktrace check
after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
