apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pdxazure-app
    name: pdxazure
  name: pdxazure-deployment
  selfLink: /api/v1/namespaces//services/pdxazure-deployment
spec:
  clusterIP: <unknown>
  ports:
  - nodePort: 32384
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pdxazure-app
    name: pdxazure
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
