apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
 name: {{ template "fullname" . }}
   chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
 template:
  metadata:
   labels:
    app: {{ template "fullname" . }}
  spec:
   containers:
     - name: {{ .Chart.Name }}
       image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
       imagePullPolicy: Always
       securityContext:
         privileged: true
       ports:
       - containerPort: 4118
         protocol: TCP
       - containerPort: 4120
         protocol: TCP
       - containerPort: 5274
         protocol: TCP
       - containerPort: 443
         protocol: TCP
       volumeMounts:
        - mountPath: /mnt/ROOT
          name: root
   volumes:
    - name: root
      hostPath:
       path: /
{{ end }}