kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-config
  namespace: kube-system
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  inputs.conf: |
    [monitor:///var/log/containers/*.log]
    host_regex = /var/log/containers/(.*)_.*_.*\.log
    sourcetype = kubernetes
  cacert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB/DCCAaGgAwIBAgIBADAKBggqhkjOPQQDAjB+MSswKQYDVQQDEyJTcGx1bmsg
    Q2xvdWQgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNp
    c2NvMRMwEQYDVQQKEwpTcGx1bmsgSW5jMQswCQYDVQQIEwJDQTEVMBMGA1UECxMM
    U3BsdW5rIENsb3VkMB4XDTE0MTExMDA3MDAxOFoXDTM0MTEwNTA3MDAxOFowfjEr
    MCkGA1UEAxMiU3BsdW5rIENsb3VkIENlcnRpZmljYXRlIEF1dGhvcml0eTEWMBQG
    A1UEBxMNU2FuIEZyYW5jaXNjbzETMBEGA1UEChMKU3BsdW5rIEluYzELMAkGA1UE
    CBMCQ0ExFTATBgNVBAsTDFNwbHVuayBDbG91ZDBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABPRRy9i3yQcxgMpvCSsI7Qe6YZMimUHOecPZWaGz5jEfB4+p5wT7dF3e
    QrgjDWshVJZvK6KGO7nDh97GnbVXrTCjEDAOMAwGA1UdEwQFMAMBAf8wCgYIKoZI
    zj0EAwIDSQAwRgIhALMUgLYPtICN9ci/ZOoXeZxUhn3i4wIo2mPKEWX0IcfpAiEA
    8Jid6bzwUqAdDZPSOtaEBXV9uRIrNua0Qxl1S55TlWY=
    -----END CERTIFICATE-----
  client.pem: |
    -----BEGIN CERTIFICATE-----
    MIICGTCCAb+gAwIBAgIEWNPalTAKBggqhkjOPQQDAjB+MSswKQYDVQQDEyJTcGx1
    bmsgQ2xvdWQgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRYwFAYDVQQHEw1TYW4gRnJh
    bmNpc2NvMRMwEQYDVQQKEwpTcGx1bmsgSW5jMQswCQYDVQQIEwJDQTEVMBMGA1UE
    CxMMU3BsdW5rIENsb3VkMB4XDTE3MDMyMzE0MjQyMVoXDTIyMDMyMjE0MjQyMVow
    gaoxMjAwBgNVBAMMKWlucHV0LXByZC1wLW5jdnczNTdtbHhtci5jbG91ZC5zcGx1
    bmsuY29tMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRUwEwYDVQQKDAxTcGx1bmsg
    Q2xvdWQxCzAJBgNVBAgMAkNBMSMwIQYJKoZIhvcNAQkBFhRjbG91ZC1lbmdAc3Bs
    dW5rLmNvbTETMBEGA1UECwwKQ2xvdWQgVGVhbTBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABGaA+jDtSeQGGIHt7v9djvJPYw8zKzRvquo86f2e7qOqZXYCMj5fsEkd
    L64CREVnL0AAff8axny34PzR9i3DLAAwCgYIKoZIzj0EAwIDSAAwRQIhAPcpLPuP
    4/xW4GZM4cluw/70YhLfxHE6+TPr3TRy8KwBAiBmOeseX86eU9Vg8syoDyKIUzXY
    YIgbPtQBQmVEYrj5Sg==
    -----END CERTIFICATE-----

    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIHeMEkGCSqGSIb3DQEFDTA8MBsGCSqGSIb3DQEFDDAOBAhHe+Kyk0xAlwICCAAw
    HQYJYIZIAWUDBAEqBBAM2xqDwkC2mTIIoi+V5AGgBIGQNXNNQk5iVeuQA/yj5AGL
    3m4Ac2JMXrl1HaMvf9WuKN9GdGJtMWVdRTOwZbu5AJNEbQMJ7j7naLR6PkhoWNQm
    In3ikTK0su2Tl1s5R25nAvaIm/Zo/u6pHs+WEnFg/0Q5KKJaP0SxgPCuT8y4MXYZ
    VpByGPhZhCLn0QMhYtCPpR9rSHm5akWQLKT3r1oKI0WT
    -----END ENCRYPTED PRIVATE KEY-----
  limits.conf: |-
    # By default a universal or light forwarder is limited to 256kB/s
    # Either set a different limit in kB/s, or set the value to zero to
    # have no limit.
    # Note that a full speed UF can overwhelm a single indexer.

    [thruput]
    maxKBps = 256
  outputs.conf: |
    [tcpout]
    defaultGroup = splunkcloud

    [tcpout:splunkcloud]
    compressed = false
    disabled = false
    server = input-prd-p-ncvw357mlxmr.cloud.splunk.com:9997
    sslCommonNameToCheck = input-prd-p-ncvw357mlxmr.cloud.splunk.com
    sslCertPath = $SPLUNK_HOME/etc/apps/splunkclouduf/default/client.pem
    sslPassword = 6f5e39864663ef601eabe4c79ad99f98
    sslRootCAPath = $SPLUNK_HOME/etc/apps/splunkclouduf/default/cacert.pem
    sslVerifyServerCert = true
    useACK = true
  server.pem: |
    -----BEGIN CERTIFICATE-----
    MIICGjCCAb+gAwIBAgIEWNPalTAKBggqhkjOPQQDAjB+MSswKQYDVQQDEyJTcGx1
    bmsgQ2xvdWQgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRYwFAYDVQQHEw1TYW4gRnJh
    bmNpc2NvMRMwEQYDVQQKEwpTcGx1bmsgSW5jMQswCQYDVQQIEwJDQTEVMBMGA1UE
    CxMMU3BsdW5rIENsb3VkMB4XDTE3MDMyMzE0MjQyMVoXDTIyMDMyMjE0MjQyMVow
    gaoxMjAwBgNVBAMMKWlucHV0LXByZC1wLW5jdnczNTdtbHhtci5jbG91ZC5zcGx1
    bmsuY29tMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRUwEwYDVQQKDAxTcGx1bmsg
    Q2xvdWQxCzAJBgNVBAgMAkNBMSMwIQYJKoZIhvcNAQkBFhRjbG91ZC1lbmdAc3Bs
    dW5rLmNvbTETMBEGA1UECwwKQ2xvdWQgVGVhbTBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABOVnGraV7wO3oWTdzWUCP72c50U8VCirD7n6zRtGuouhE30tYkT4Chkh
    tjgS128TEZms0hBtUWbmgSiMDm5iT6YwCgYIKoZIzj0EAwIDSQAwRgIhAMeNtadH
    Bp9T5CxgIiDvZvkVfUF/w739Up7EV9lbVLipAiEA5cSm1+RrBc1z+7+e5iXtdKJL
    BMIMMmtOvFURHLMkfd4=
    -----END CERTIFICATE-----

    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIHeMEkGCSqGSIb3DQEFDTA8MBsGCSqGSIb3DQEFDDAOBAilgzv6pgXDQAICCAAw
    HQYJYIZIAWUDBAEqBBB44CPS0CxSzW6hlMUA3ZkjBIGQewH7v581M+HmoeBAUM4R
    jKO7SeFR2g9MsyC179f8knPyXBL1DAfY0156d/3lkv2kvsKOLTieHSwWnLviFiRh
    uXCj/PbU2kXqRDC/NomIgI0jLPDl9s8+lGCUsfCFPRKjPg1DCW69mHpkTgZgTVrZ
    C5CrSr+7heCpauKVWjrk5qkhRASjp2fNpZSFGjRjGRC7
    -----END ENCRYPTED PRIVATE KEY-----